version: '3'
services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    command: pipenv run tracking

  endpoint:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    command: pipenv run endpoint



